# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
