# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 18:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_file_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_from',
            field=models.DateField(blank=True, default=datetime.datetime(1990, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='document',
            name='file_to',
            field=models.DateField(blank=True, default=datetime.datetime(1990, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
