# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 06:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=255)),
                ('employee_id', models.CharField(blank=True, max_length=255)),
                ('attendence_date', models.DateField(blank=True, default=datetime.datetime(1990, 1, 1, 0, 0))),
                ('work_time', models.DateTimeField()),
            ],
        ),
    ]
