# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_employee_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='attendence_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
