# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171008_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_time',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
