# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171008_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_dept',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_tower',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
