# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171009_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_tower',
            new_name='tower',
        ),
    ]
