# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 07:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='attendence_date',
            field=models.DateField(blank=True, default=datetime.datetime(1990, 1, 1, 0, 0)),
        ),
    ]
