# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171025_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeComplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True)),
                ('Time', models.TimeField(blank=True)),
                ('SiteCode', models.IntegerField(blank=True)),
                ('Cardid', models.IntegerField(blank=True)),
                ('Empid', models.IntegerField(blank=True)),
                ('EmpName', models.CharField(blank=True, max_length=255)),
                ('Department', models.CharField(blank=True, max_length=255)),
                ('Type', models.CharField(blank=True, max_length=255)),
                ('CID', models.IntegerField(blank=True)),
                ('Gate', models.CharField(blank=True, max_length=255)),
                ('InOut', models.CharField(blank=True, max_length=255)),
                ('Remark', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
