# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_employeecomplete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecomplete',
            old_name='Cardid',
            new_name='cardid',
        ),
        migrations.RenameField(
            model_name='employeecomplete',
            old_name='CID',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='employeecomplete',
            old_name='Date',
            new_name='dat',
        ),
        migrations.RenameField(
            model_name='employeecomplete',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employeecomplete',
            old_name='Empid',
            new_name='empid',
        ),
        migrations.RenameField(
            model_name='employeecomplete',
            old_name='EmpName',
            new_name='empname',
        ),
        migrations.RenameField(
            model_name='employeecomplete',
            old_name='Gate',
            new_name='gate',
        ),
        migrations.RenameField(
            model_name='employeecomplete',
            old_name='InOut',
            new_name='inout',
        ),
        migrations.RenameField(
            model_name='employeecomplete',
            old_name='Remark',
            new_name='remark',
        ),
        migrations.RenameField(
            model_name='employeecomplete',
            old_name='SiteCode',
            new_name='sitecode',
        ),
        migrations.RenameField(
            model_name='employeecomplete',
            old_name='Time',
            new_name='tim',
        ),
        migrations.RenameField(
            model_name='employeecomplete',
            old_name='Type',
            new_name='typ',
        ),
    ]
