# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20171121_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_dept',
            new_name='dept',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_response',
            field=models.CharField(default='No Recorded response', max_length=255),
        ),
    ]
