# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180110_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='records',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
