# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_document_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='day',
            field=models.DateField(blank=True, default=None),
        ),
    ]
