# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_employee_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='day',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
