version: '3.3'
services:
  # db:
  #   image: postgres
  swipeweb:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    image: dtr.${DOCKER_DOMAIN}/${DTR_ORG_NAME}/${DTR_REPO_NAME}:${TAG}
    ports:
      - "8000"
    labels:
      com.docker.ucp.mesh.http: "true"
    volumes:      
      - swipe-automation:/app
    # depends_on:
    #   - db
    networks:
      default:
      hrm:    
    deploy:
      labels:
        com.docker.ucp.mesh.http: "external_route=http://${LAUNCH_URL_HOST},internal_port=8000"
        com.docker.ucp.access.label: ${DDC_COLLECTION}
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
       condition: on-failure
volumes:
  swipe-automation:
    external: false
    driver: pxd
    driver_opts:
      size: 2
      repl: 3
      sticky: 1
      shared: 0
networks:
  default:
  hrm:
    external:
      name: ${DDC_NETWORK}
